export const errorMessage = {
   BOTH_PASSWORD_SHOULD_MATCH: "New Password and Confirm Password should match",
   CANCELING_UPLOADING: "Canceling File Uploading",
   CANNOT_REVERT: "Cannot revert before saving",
   CHUNK_UPLOAD_FAILED: "Something went wrong while upload retry again",
   CLIENT_ALREADY_EXISTS: "Client already exists",
   EMAIL_ALREADY_EXISTS: "Email already exists",
   HAS_DUPLICATE_COLUMN: " has duplicate table column.",
   INTERNAL_SERVER_ERROR: "Internal server error.",
   INVALID_PASSWORD: "Invalid Credentials",
   IS_OLD_PASSWORD_VALID: "The entered old password isn't valid.",
   LOGIN_ERROR: "Please enter the correct email  and password",
   LINK_EXPIRED_ERROR_MESSAGE: "Request failed with status code 410",
   OLDPASSWORD_AND_NEWPASSWORD_NOT_SAME: "Old password and new password should not same.",
   OLD_PASSWORD_IS_SAME_AS_CURRENT_PASSWORD: "The given password shouldn't match with the previous password.",
   PASSWORD_NOT_MATCH_REQUIREMENT: "The new password does not meet the password policy requirements",
   PLEASE_COMPLETE_FIELD_MAPPING: "Please complete the field mapping",
   PLEASE_COMPLETE_FIELDMAPPING_TO_CONTINUE: "Please complete the field mapping to continue",
   PLEASE_CONTACT_ADMIN: "Please contact Cenozon support at support@cenozon.com",
   PLEASE_ENTER_BOTH_PASSWORD: "Please enter the new password & confirm password",
   PLEASE_ENTER_CLIENT_NAME: "Please enter the client name",
   PLEASE_ENTER_CONFIRM_PASSWORD: "Please enter the confirm Password",
   PLEASE_ENTER_CORRECT_MAIL_FORMAT: "Please enter the correct email format",
   PLEASE_ENTER_DIAMETER: "Please enter the outer diameter",
   PLEASE_ENTER_EMAIL: "Please enter the email",
   PLEASE_ENTER_MAIL_ID: "Please enter the email",
   PLEASE_ENTER_MAIL_ID_AND_PASSWORD: "Please enter the email and password",
   PLEASE_ENTER_MAXIMUM_PRESSURE: "Please enter the maximum operating pressure",
   PLEASE_ENTER_MINIMUM_STRENGTH: "Please enter the specified minimum yield strength",
   PLEASE_ENTER_NEW_PASSWORD: "Please enter the new password",
   PLEASE_ENTER_OLD_PASSWORD: "Please enter the old password",
   PLEASE_ENTER_PASSWORD: "Please enter the password",
   PLEASE_ENTER_ROLE_NAME: "Please enter the role name",
   PLEASE_ENTER_USERNAME: "Please enter the user name",
   PLEASE_ENTER_VALID_USERNAME: "Please enter a valid username",
   PLEASE_ENTER_VENDOR_NAME: "Please enter the vendor name",
   PLEASE_GIVE_VALID_INPUT: "Please fill the valid data",
   PLEASE_NAVIGATE_TO_FIRST_STEP: "Please navigate to first step",
   PLEASE_SAVE_TO_VIEW_SUMMARY_DASHBOARD: "Please save your data to view ILI Summary Dashboard",
   PLEASE_SELECT_BEGIN_DATE: "Please select the begin date",
   PLEASE_SELECT_END_DATE: "Please select the end date",
   PLEASE_SELECT_ONE_VERSION: "Please select a single ILI Inspection",
   PLEASE_SELECT_ROLE: "Please select atleast one role",
   PLEASE_SELECT_TABLE_COLUMN: "Please select Table column for ",
   PLEASE_SELECT_SUB_UNIT: "Please select the sub unit",
   PLEASE_SELECT_UNIT: "Please select the unit",
   PLEASE_SELECT_VENDOR: "Please select the vendor",
   PLEASE_SELECT_VERSION: "Please select a version to override",
   PLEASE_UPLOAD_EXCEL: "Please upload the file",
   PLEASE_UPLOAD_VALID_EXCEL: "Please upload a valid file",
   PLEASE_WAIT_UNTIL_UPLOAD: "Please wait until file has been uploaded",
   PLEASE_PROVIDE_VALID_INPUT_PRECISION_4_0: "Please give the valid input with (4,0) precision",
   PLEASE_PROVIDE_VALID_INPUT_PRECISION_MAOP_COLUMN: "Please give the valid input with (5,0) precision",
   PLEASE_PROVIDE_VALID_POSITIVE_INPUT_MAOP_COLUMN: "Please enter the positive value for maximum operating pressure",
   PLEASE_PROVIDE_VALID_POSITIVE_INPUT_SMYS_COLUMN: "Please enter the positive value for specified minimum yield strength",
   PLEASE_PROVIDE_VALID_POSITIVE_INPUT_OD_COLUMN: "Please enter the positive value for outer diameter",
   PLEASE_PROVIDE_VALID_INPUT_PRECISION_6_4: "Please give the valid input with (6,4) precision",
   PLEASE_PROVIDE_VALID_INPUT_PRECISION_7_3: "Please give the valid input with (7,3) precision",
   PLEASE_PROVIDE_VALID_INPUT_PRECISION_8_3: "Please give the valid input with (8,3) precision",
   PLEASE_PROVIDE_VALID_INPUT_PRECISION_OD_COLUMN: "Please give the valid input with (8,4) precision",
   PLEASE_SELECT_UNIT_AND_SUB_UNIT: "Please select unit and sub unit before saving",
   ROLE_ALREADY_EXISTS: "Role already exists",
   UNABLE_TO_PARSE_EXCEL: "Error in parsing the file",
   UNABLE_TO_REVERT: "Unable to revert the action",
   UNABLE_TO_UPDATE_MATCHING_DETAILS: "Unable to update matching details",
   UNABLE_TO_FETCH_SUMMARY_DETAILS: "Unable to fetch ILI Summary Details",
   UNABLE_TO_FETCH_QC_DASHBOARD: "Unable to load QC Dashboard",
   UPLOAD_CANCELLED_FAIL: "Cancel upload failed",
   UNIT_MISMATCH: "The targeted unit",
   UNIT_MISMATCH_TARGET: "is does not matched with the selected unit",
   UPLOAD_CANCELLED_SUCCESS: "Upload cancelled successfully",
   UPLOAD_COMPLETE_FAIL: "Upload complete failed",
   VENDOR_ALREADY_EXISTS: "Vendor already exists"
};

export const displayText = {
   ACTIVE: "Active",
   ACCOUNT: "Account",
   ADD: "Add",
   ADDRESS: "Address",
   ADD_APP_ADMIN: "Add Application Administrator",
   ADD_CLIENT: "Add Client",
   ADD_OPERATIONALAREA_ROLE: "Add Area",
   ADD_OPERATIONAL_AREA: "Add Operational Area",
   ADD_ROLE: "Add Role",
   ADD_USER: "Add User",
   ADD_VENDOR: "Add Vendor",
   ADMIN_TABLE: "applicationusers_table",
   ALERT: "Alert",
   ALL: "All",
   API: "api",
   APPLICATION_ADMIN: "App Admin",
   APPLICATION_JSON: "application/json",
   APPLICATION_USER_TABLE: "Application User table",
   APP_ADMIN: "Application Admin",
   APP_USER_BREADCRUMBS: "Application Administrator",
   ARCHIVED: "ARCHIVED",
   ASC: " asc",
   ASCENDING: "asc",
   AUTO_COMPLETE: "autocomplete",
   AVG_TEMP: "Average Temperature",
   BACK: "Back",
   BACK_TO_LOGIN: "Back to login",
   BEARER: "Bearer",
   BEGIN_DATE: "Begin Date",
   BLUR: "blur",
   CANCEL: "Cancel",
   CENOZON_LOGO: "Cenozon logo",
   CHANGE_PASSWORD: "Change Password",
   CHOOSE_INSPECTION: "Choose ILI Inspection",
   CITY: "City",
   CLIENT_ID: "clientId",
   CLIENTSGUID: "clientsGuid",
   CLIENT_ADMIN: "Client Admin",
   CLIENT_MANAGEMENT: "Client Management",
   CLIENT_NAME: "clientname",
   CLIENT_SWITCHING: "Switching Client...",
   CLIENT_TABLE: "clients_table",
   CLOSE: "CLOSE",
   CLUSTER_RULE_CL: "Cluster Rule",
   COMMENTS: "Comments",
   COMPANY_PROFILE: "Company Profile",
   CONFIRMATION_TEXT: "Confirmation",
   CONFIRMPASSWORD: "Confirm Password",
   CONFIRM_EXISTING_VERSION: "Are you sure want to choose existing version",
   CONFIRM_PASSWORD: "confirmPassword",
   CONSULTANTS: "Consultants",
   CONTINUE: "Continue",
   CONTINUE_CLICK: "Continue Click",
   COUNTRY: "Country",
   COUNTRY_GUID: "countryGuid",
   CREATING_APP_USER: "Creating Application User...",
   CURRENT: "Current",
   DASHBOARD_FIELDS: "Data Over-rides",
   DATAIMPORT: "Data Import",
   DATA_ADMIN: "Data Admin",
   DATE_FORMAT: "MMM dd, yyyy",
   DEFAULT: "default",
   DEFAULT_PARENTID: "00000000-0000-0000-0000-000000000000",
   DELETE: "Delete",
   DELETE_CLIENT_CONFIRMATION_MESSAGE: "Are you sure you want to delete this client?",
   DELETE_CLIENT_ROLE: "Delete Client",
   DELETE_OPERATIONALAREA_ROLE: "Delete Area",
   DELETE_OPERATIONAL_AREA_CONFIRMATION_MESSAGE: "Are you sure you want to delete this operational area?",
   DELETE_ROLE: "Delete Role",
   DELETE_ROLE_CONFIRMATION_MESSAGE: "Are you sure you want to delete this role?",
   DELETE_USER_APPLICATION_CONFIRMATION_MESSAGE: "Are you sure you want to delete this application administrator?",
   DELETE_USER_CONFIRMATION_MESSAGE: "Are you sure you want to delete this user?",
   DELETE_USER_ROLE: "Delete User",
   DELETE_VENDOR_CONFIRMATION_MESSAGE: "Are you sure you want to delete this vendor?",
   DELETE_VENDOR_ROLE: "Delete Vendor",
   DESC: " desc",
   EDIT: "Edit",
   EDIT_APPLICATION_USER: "Edit Application Administrator",
   EDIT_CLIENT: "Edit Client",
   EDIT_OPERATIONALAREA_ROLE: "Edit Area",
   EDIT_OPERATIONAL_AREA: "Edit Operational Area",
   EDIT_PROFILE: "Edit Profile",
   EDIT_ROLE: "Edit Role",
   EDIT_USER: "Edit User",
   EDIT_VENDOR: "Edit Vendor",
   EMAIL: "Email",
   EMAIL_FIELD_DEFAULT_WIDTH: 40,
   END_DATE: "End Date",
   ENTER: "Enter",
   ENTER_ROLENAME: "Enter role name...",
   ERROR_IN_FETCHING_QC_DASHBOARD_DATA: "Error in fetching QC dashboard data",
   ERROR_IN_SAVING_QC_DASHBOARD_DATA: "Error in saving QC dashboard data",
   EXCEL_COLUMN_UNIT: "excelColumn",
   EXCEL_COLUMN: "Excel Column",
   EXCEL_COLUMNS: "ExcelColumns",
   EXCEL_UNIT: "Excel Unit",
   EXCEL_UNIT_NAME: "excelUnitName",
   FALSE: "false",
   FETCHING_USER_DATA: "Fetching User Data...",
   FETCHING_SUMMARY_DETAILS: "Fetching summary details...",
   FEATURE_LIST_DATA: "FEATURE_LIST_DATA",
   FEATURE_TYPE_COLUMN: "ANOMALY_TYPE_CL",
   FEATURE_TYPE: "Feature Type",
   FIELD_MAPPING_IGNORED: `${null}.${null}`,
   FIELD_MAPPING_VALIDATION: "Field Mapping Validation",
   FIELD_OPERATOR_ROLES: "Field Operators",
   FILE_NAME: "fileName",
   FILE_UPLOADING: "File is uploading...",
   FILL_IN: "fill-in",
   FILL_MISSING: "Fill-in where missing",
   FILL_MISSING_FEATURE_TYPES: "Fill-in where missing",
   FORGOT_PASSWORD_LINK_TEXT: "Forgot password?",
   FROM_FIELDMAPPING: "From Field Mapping",
   FROM_LOC: "From Loc",
   FROM_LOCATION_DESC: "From Location",
   HI: "Hi",
   HISTORICAL: "Historical",
   HOME: "Home",
   ILI_DATA_TABLE: "ILI_DATA",
   ILI_OPERATIONAL_AREA: "operationalArea",
   ILI_SUMMARY: "ILISummary",
   ILI_SUMMARY_DASHBOARD: "ILI Summary Dashboard",
   ILI_SUMMARY_SHEET_WARNING_DESCRIPTION: "Please select at least one sheet to proceed further",
   ILI_UNIT: "unit",
   ILI_VENDOR: "vendor",
   ILI_VERSION: "version",
   IMPORT_DATE: "Import Date",
   INITIAL_VALUE: "0",
   INSPECTION_ID: "Inspection Id",
   INTEGRITY_ENGINEER: "Integrity Engineer",
   IN_ACTIVE: "InActive",
   ISACTIVE: "IsActive",
   ISO_DATE_FORMAT: "YYYY-MM-DDTHH:mm:ss.SSS[Z]",
   IS_LOAD_FIRST: "isFirstLoad",
   IS_SAVE_CLICK: "isSaveClick",
   JOINT_NUMBER: "Joint Number",
   LIST_OF_ROLE_NAME: "list of role name",
   LOADING: "Loading ...",
   LOADING_PREVIEW: "Loading Preview...",
   LOADING_PROFILE: "Loading Profile...",
   LOADING_ILI_SUMMARY_DASHBOARD: "Loading ILI Summary Dashboard...",
   LOADING_MENU: "Loading Menu...",
   LOADING_SUB_UNITS: "Loading Sub Units...",
   LOGIN: "Login",
   LOGIN_TO_CONTINUE: "Login to continue",
   LOGOUT: "Logout",
   LOGOUT_LOADER: "Logging Out...",
   LOGOUT_REQUIRED: "Logout Required",
   LOWERCASE_LETTER_a_z: "Atleast one lowercase letter (a - z)",
   MAIL_SENT_SUCCESS: "Mail sent successfully!",
   MANGEMENT_ROLES: "Management",
   MAOP_COLUMN: "B31G_MAOP",
   MAPPING_COLUMN: "Mapping Column",
   MASTER: "master",
   MATCHING_PERCENTAGE: "Match",
   MAX_OPERATING_PRESSURE: "Maximum Operating Pressure",
   MAX_TEMP: "Maximum Temperature",
   MAX_YIELD_STRENGTH: "Specified Maximum Yield Strength",
   MIN_YIELD_STRENGTH: "Specified Minimum Yield Strength",
   MIN_TEMP: "Minimum Temperature",
   MODEL: "Model",
   MY_PROFILE: "My Profile",
   NAME: "name",
   NEWPASSWORD: "newPassword",
   NEW_PASSWORD_ATTRIBUTE: "new-password",
   NEW_PASSWORD: "New Password",
   NO: "No",
   NOTES: "Notes",
   NO_DATA_FOUND: "No data found",
   NON_APPLICABLE: "n/a",
   NUMBERS_0_9: "Atleast one number (0 - 9)",
   NULL: "null",
   Next: "Next",
   OD_COLUMN: "OUTSIDE_DIAMETER",
   OK: "OK",
   OLD_PASSWORD: "Old Password",
   OPERATIONAL_AREA: "Operational Area",
   OPERATIONAL_AREA_EXISTS: "Operational area already Exists",
   OPERATIONAL_AREA_MANAGEMENT: "Operational Area Management",
   OPERATIONAL_SELECT: "Select Operational Area",
   OUTER_DIAMETER: "Outer Diameter",
   OVERIDE: "overide",
   OVERIDE_ALL_VALUE: "Overide all values",
   PANEL: "panel",
   PASSWORD: "Password",
   PASSWORD_FIELD_MAX_WIDTH: 130,
   PASSWORD_FIELD_WIDTH: 70,
   PASSWORD_GUIDELINES: "Password Guidelines",
   PASSWORD_INSTRUCTION: "Password must be at least 8 characters in length",
   PASSWORD_MUST_CONT_ALL_FOLLOW: "Password must contain all of the following:",
   PASSWORD_UPDATED: "Password updated !",
   PASSWORD_UPDATING: "Password Updating...",
   PHONE: "Phone",
   PHONE_NUMBER_LENGTH: 15,
   PLEASE_ENTER_OPERATIONAL_AREA: "Please enter the operational area ",
   PLEASE_LOGOUT_MESSAGE: "Please logout to see the client in the configuration",
   PLEASE_SELECT_VERSION_TO_OVERRIDE: "Please select any of the following versions to override",
   PLEASE_TRY_AFTER_SOMETIMES: "Please try again later",
   POSTALCODE: "Postal Code",
   PROJECT_NO: "Project No",
   PROJECT_NUMBER: "Project Number",
   PROVINCE_STATE: "Province/State",
   QC_DASHBOARD_LOADER: "QC results being generated...",
   QC_DASHBOARD_PREVIOUS_VERSION_LOADER: "Loading previous versions QC dashboard...",
   QC_DASHBOARD_VALIDATION: "QC Dashboard Validation",
   QUANTITY: "Quantity",
   QUANTITY_NAME: "quantityName",
   RATED_MAX_VELOCITY: "Rated Max Velocity",
   RATED_MAX_WEIGHT: "Rated Max Weight",
   REPORT_DATE: "Report Date",
   RESEND_FORGOTPASSWORD_EMAIL: "Resend email",
   RESET_PASSWORD_TOKEN_EXPIRED: "Reset password token expired!",
   RESOLUTION: "Resolution",
   RETRY: "Retry",
   REVERT: "Revert",
   REVERT_QC_DASHBOARD_DATA: "Reverting QC dashboard data",
   REVERT_SUCCESS: "Successfully reverted",
   ROLE: "roles",
   ROLE_ALREADY_EXIST: "This role name already exists",
   ROLE_GUIDE: "rolesGuid",
   ROLE_MANAGEMENT: "Role Management",
   ROLE_NAME: "roleName",
   SAMPLING_FREQUENCY: "Sampling Frequency",
   SAVE: "Save",
   SAVED_DETAILS: "SavedDetails",
   SAVING_VENDOR_OPERATIONAL_AREA: "Saving vendor and operational area...",
   SAVE_WITHOUT_VALIDATION: "Save without validation",
   SAVE_WITH_VALIDATION: "Save with validation",
   SAVING: "Saving...",
   SAVING_COMPLETED: "Save Completed",
   SAVING_QC_DASHBOARD_DATA: "Saving ILI data...",
   SAVING_TEMPLATE: "Saving Template...",
   SAVING_TEMPLATE_ERROR: "Error Saving template",
   SEARCHING_USER_DATA: "Searching User Data...",
   SEARCH_DATA: "Search Previous Versions",
   SELECT: "Select",
   SELECT_ALL: "Select All",
   SELECT_ALL_CLIENT_DROPDOWN: "Select all client dropdown",
   SELECT_CLIENT: "Select Client",
   SELECT_EXCEL_FILE: "Choose File (.csv, .xls, .xlsx, .xlsm)",
   SELECT_INSPECTION: "Select ILI Inspection",
   SELECT_UNIT: "Unit",
   SELECT_VERSION: "Select Version",
   SELECTED_VENDOR_NAME: "vendorName",
   SEND_LINK: "Send Link",
   SENDING_MAIL: "Sending Mail...",
   SENSOR_CL: "Sensor CL",
   SENSOR_SPACING_MAX: "Sensor Spacing Maximum",
   SENSOR_SPACING_MIN: "Sensor Spacing Minimum",
   SET_PASSWORD_MEDIUM_WIDTH: 108,
   SHEET_INDEX: "sheetIndex",
   SHEET_NAME: "sheetName",
   SIMPLE_TAB: "simple-tab",
   START_INDEX: "startIndex",
   STATUS: "Status",
   SUB_UNIT_OF_MEASURE: "Sub Unit of Measure",
   SUCCESS: "Success !",
   SUMMARY_PROJECT_NO: "projectNumber",
   SUMMARY_BEGIN_DATE: "beginDate",
   SUMMARY_END_DATE: "endDate",
   SUMMARY_TOOL_TYPE: "toolTypeCl",
   SUMMARY_TOOL_VENDOR: "toolVendorCl",
   SUMMARY_FROM_LOCATION: "fromLocation",
   SUMMARY_TO_LOCATION: "toLocation",
   SYMBOLS_OR_SPECIAL: "Atleast one symbol or special character",
   SMYS_COLUMN: "SMYS",
   TABLE_COL: "Table column",
   TABLE_COLUMN: "tableColumn",
   TABLE_UNIT: "tableUnit",
   TABLE_UNIT_NAME: "tableUnitName",
   TAB_PANEL: "tabpanel",
   TARGET_UNIT: "Target Unit",
   TEXT: "text",
   TOGGLE_PASSWORD_VISIBILITY: "toggle password visibility",
   TOOL_OPERATIONAL_AREA_CL: "Operational Area",
   TOOL_TYPE: "Tool Type",
   TOOL_TYPE_CL: "Tool Type",
   TOOL_VENDOR_CL: "Vendor",
   TO_LOC: "To Loc",
   TO_LOCATION_DESC: "To Location",
   TRUE: "True",
   UNIT_OF_MEASURE: "Unit of Measure",
   UNIT_NAME: "excelUnit",
   UNIT_TYPE: "unitType",
   UPPERCASE_LETTER_A_Z: "Atleast one uppercase letter (A- Z)",
   URL_TOKEN: "?token=",
   URL_USER_GUID: "?userGuid=",
   URL_INDEX: 1,
   USERNAME: "username",
   USER_COUNT: "user count",
   USER_GUID: "usersGuid",
   USER_INFO_LABEL: "Select the sheet to proceed for field mapping",
   USER_MANAGEMENT: "User Management",
   USER_NAME: "User Name",
   USER_NAME_ICON: "user name icon",
   USER_TABLE: "users_table",
   USER_TABLE_HEADER: "user",
   VENDOR_CL: "Vendor",
   VENDOR_ID: "VendorId",
   VENDOR_MANAGEMENT: "Vendor Management",
   VENDOR_NAME: "Vendor Name",
   VENDOR_SELECT: "Select Vendor",
   VENDOR_TABLE: "vendors_table",
   VERSION: "Choose Version",
   VERSION_ID: "Version Id",
   VERSION_NO: "Version No",
   VERSION_NUMBER: "Version Number",
   VERSION_OVERRIDE: "Version Override",
   VERTICAL_TAB: "vertical-tab",
   WARNING: "Warning",
   WARNING_CHANGE_CLIENT_MESSAGE: "Are you sure you want to continue, there are unsaved changes?",
   WARNING_REVERT_SAVE: "Clicking on revert will erase all the data. Do you still want to continue?",
   WARNING_LENGTH_DATA: "Would you like to correct the joint length based on start and end odometer?",
   WARNING_REDIRECT_FIRST_STEP: "After completing the save you can't go back to step 2 and step 3. Do you want to go to Step 1?",
   YEAR_MONTH_DAY_FORMAT: "YYYY-MM-DD",
   YES: "Yes"
};

export const formDataInput = {
   excelTemplate: "excelTemplate",
   fieldInput: "fieldinput",
   fileName: "fileName",
   iliFieldDetails: "iliFieldDetails",
   importDate: "importDate",
   inspectionGuid: "inspectionGuid",
   iliInspectionDetails: "iliInspectionDetails",
   iliSaveInput: "ilisaveinput",
   isFirstLoad: "isFirstLoad",
   isJointLength: "IsJointLength",
   isJointLengthOverWrite: "IsJointLengthOverWrite",
   isLastJointLength: "IsLastJointLength",
   isSaveClick: "isSaveClick",
   isValidated: "isValidated",
   isVersionOverWrite: "isVersionOverWrite",
   qcInput: "qcInput",
   savedInspectionGuid: "savedInspectionGuid",
   reportDate: "reportDate",
   sheetIndex: "sheetIndex",
   startIndex: "startIndex",
   vendorGuid: "vendorGuid",
   versionId: "versionId",
   versionNotes: "versionNotes"
};

export const regularExpression = {
   EMAIL: /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/,
   EXCEL_FORMATS: /\.(xlsx|xls|csv|xlsm)$/,
   GET_DATA_INSIDE_PARENTHESIS: /\(([^)]+)\)/,
   PASSWORD: /^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[^a-zA-Z0-9])(?!.*\s).{8,15}$/,
   PHONE: /[^0-9\+\ \/]/g,
   CITY: /[0-9]/g,
   CITY_CHECK_CHARACTER: /[^a-zA-Z ]/g,
   GET_DATA_BETWEEN_BRACKETS: /\(([^)]+)\)/,
   REMOVE_DOUBLE_QUOTES: /['"]+/g,
   REGEX_RESULT_INDEX: 1
};

export const statusCode = {
   CODE_200: 200,
   CODE_201: 201,
   CODE_208: 208,
   CODE_401: 401,
   CODE_400: 400,
   CODE_GONE_ERROR: 410
};

export const clientProfileLabelText = {
   ADDRESS: "Address",
   CITY: "City",
   CLIENTNAME: "Client Name",
   COUNTRY: "Country",
   EMAIL: "Email",
   MAINCONTACT: "Main Contact",
   PHONE: "Phone",
   POSTAL_CODE: "Postal code",
   STATE: "State"
};

export const initialPageLimit = 10;

export const initialPage = 0;

//object Label constants
export const navIcon = "icon"
export const indeterminateLabel = "indeterminate";
export const isActiveLabel = "isActive";
export const clientsGuidLabel = "clientsGuid";
export const isTabChecked = "isTabChecked";
export const index = "index";
export const initialSheetIndex = 0;
export const initialCharacterIndex = 0;
export const toPath = "to";

export const defaultNode = {
   "id": 1,
   "filename": "OPERATING AREAS",
   "children": []
};

export const apiRouter = {
   ADD_APP_ADMIN_USER: "AddAppAdminUser",
   ADD_ROLE: "AddRoleFeatures",
   ADDUSER: "AddUser",
   AUTHENICATE: "authenticate",
   CASCADE_DATA_SAVE: "CascadeAndSaveILIData",
   CHANGEPASSWORD: "ChangePassword",
   CHECK_APP_USEREMAIL_EXISTS: "CheckAppAdminEmailExists",
   CHECK_CLIENT_NAME_EXISTS: "CheckClientName",
   CHECK_ROLE_NAME_EXISTS: "CheckRoleNameExist",
   CHECK_PASSWORD: 'CheckPassword',
   CHECK_USEREMAIL_EXISTS: "CheckUserEmailExists",
   CHECK_VENDOR_NAME_EXISTS: "CheckVendorExists",
   CHUNK_NUMBER: "chunkNumber",
   CLIENT: "Clients",
   CLIENT_GUID: "clientGuid",
   CLIENT_PROFILE: "GetClient",
   CLIENT_URL_ROLES: "/client/",
   COMMON: "Common",
   COMMON_USER_PREFERENCE: "GetUserPreferences",
   COUNTRY: "Country",
   GET_FILE_NAME: "GetFileName",
   DATA_IMPORT: "/data-import",
   DATA_SUMMARY: "DataSummary",
   DELETE_ROLE: "DeleteRoleFeatures",
   DELETE_ORIGINAL_FILE: "deleteOriginalFile",
   EMAIL: "email",
   EXCEL_IMPORT: "ExcelDataImport",
   FEATURES: "Features",
   FIELD_MAPPING: "FieldMapping",
   FILE_NAME: "fileName",
   FILE_UPLOAD: "FileUploader",
   FORGOT_PASSWORD: "ForgotPassword",
   GET_ALL_FEATURES: "GetAllFeatures",
   GET_ALL_UNITS: "GetAllUnits",
   GET_ANOMALY_CATEGORY: "GetAnomalyCategory",
   GET_APP_ADMIN_USERS: "getappadminusers",
   GET_DATA_SUMMARY_DASHBOARD: "GetDataSummaryDashboard",
   GET_FIELD_MATCHING: "GetFieldMatching",
   GET_OPERATIONAL_AREA: "OperationalArea",
   GET_OPERATIONAL_AREA_LIST: "GetOperationalAreas",
   GET_QUALITY_CONTROL_DASHBOARD: "QualityControlDashboardData",
   GET_QUANTITY: "GetUnitsByQuantity",
   GET_ROLE_BY_ID: "GetRoleFeaturesById",
   GET_ROLE_FEATURES: "GetRoleFeatures",
   GET_STATEBY_COUNTRY: "GetStatesByCountry",
   GET_SUMMARY_LIST: "GetILISummaryFields",
   GET_TABLE_UNITS: "Gettableunits",
   GET_USER: "getuser",
   GET_USER_DETAIL: "getuserdetail",
   GET_USER_PROFILE: "GetUserProfile",
   GET_VENDORS: "GetVendors",
   ID: "id",
   ILI_DATA_SAVE: "ILIDataSave",
   ILI_VERSIONING: "ILIVersionSearch",
   IMPORT_EXCEL_DATA: "ImportExcelData",
   INSERT_NEW_TEMPLATE: "InsertNewTemplate",
   IS_ACTIVE: "isActive",
   IS_ASC: "isAsc",
   LOGIN: "/login",
   MENU: "menu",
   MY_PROFILE: "/my-profile",
   OPERATIONAL_AREA_GUID: "operationalAreaGuid",
   OPERATIONAL_AREA_URL_FOR_ROLES: "/operational-area",
   ORDER_BY: "orderBy",
   PAGE_NUMBER: "pageNumber",
   PAGE_SIZE: "pageSize",
   QUALITY_CONTROL_DASHBOARD: "QualityControlDashboard",
   GET_CONVERTED_VALUE: "GetUnitConversion",
   REVERT_ILI_DATA: "RevertILIData",
   REFRESH_TOKEN: "RefreshToken",
   RESET_PASSWORD: "ResetPassword",
   REVOKE_TOKEN: "RevokeToken",
   ROLE: "Roles",
   ROLE_UPDATE: "UpdateRoleFeatures",
   ROLE_URL: "role-management",
   ROLES: "roles",
   ROLLBACK_DATA: "RollbackData",
   RUN_LIST: "GetILIRunList",
   SAVE_VENDOR_OPERATIONAL: "InsertVendorOperationalDetails",
   SEARCH_TEXT: "searchText",
   SENDEMAIL: "ResetPasswordSendEmail",
   STATE: "State",
   SUCCESS_UPDATE: "/success-update",
   UNIT: "GetUnitQuantities",
   UPDATE_PASSWORD: "updatepassword",
   UPDATE_USER_PROFILE: "UpdateUserProfile",
   UPLOAD_CANCEL: "DeleteFile",
   UPLOAD_CHUNKS: "UploadChunks",
   UPLOAD_COMPLETE: "UploadComplete",
   USER_MANAGEMENT_URL_FOR_ROLES: "/user-management",
   USERS_GUID: "usersGuid",
   USERS: "users",
   VENDORS: "Vendors",
   VENDOR_GUID: "vendorsGuid",
   VENDOR_NAME: "vendorname"
};

export const sessionStorageKey = {
   ADMIN_PREF: "admin_pref",
   CLIENT_DETAILS: "client-details",
   CLIENT_PREF: "client_pref",
   SELECTED_CLIENT: "selected_client",
   TOKEN: "token",
   USER_CURRENT_CLIENT_DETAILS: "user-currentclient-details",
   USER_DETAILS: "user-details",
   USER_PREF: "user_pref",
   USER_ROLES: "user-roles",
   VENDOR_PREF: "vendor_pref"
};

export const dataTypeCheck = {
   OBJECT: "object",
   STRING: "string"
};

export const stringManipulationCheck = {
   COMMA_OPERATOR: ",",
   DECREMENT_OPERATOR: "-",
   DOT_OPERATOR: ".",
   EMPTY_STRING: "",
   INCREMENT_OPERATOR: "+",
   SINGLE_SPACE_STRING: " ",
   UNDERSCORE_OPERATOR: "_",
   PARENTHESIS_OPEN: "(",
   PARENTHESIS_CLOSE: ")",
   PIPE_OPERATOR: "|",
   PERCENTAGE: "%",
   ASSIGNTO_OPERATOR: "=",
   DIVISION_OPERATOR: "/"
};

export const graphBackgroundColors = [
   "#36a2eb",
   "#4bc0c0",
   "#ff6384",
   "#ffce56",
   "#9966ff",
   "#ff9f40"
];

export const loaderMessages = [
   "Data being validated...",
   "Data importing..."
];

export const routerConstants = {
   LOGIN: "Login Page",
   FORGOT_PASSWORD_URL: "/forgot-password",
   FORGOT_PASSWORD: "Forgot Password",
   SET_PASSWORD_URL: "/set-password",
   SET_PASSWORD: "Set Password",
   SUCCESS_UPDATE_URL: "/success-update",
   SUCCESS_UPDATE: "Success Set Password",
   SUCCESS_MAIL_SEND_URL: "/success-mailsend",
   SUCCESS_MAIL_SEND: "Success Mail Send",
   MY_PROFILE_URL: "my-profile",
   CLIENT_MANAGEMENT_URL: "/client-management",
   ROLE_MANAGEMENT_URL: "/role-management",
   VENDOR_MANAGEMENT_URL: "/vendor-management",
   APPLICATION_ADMIN_URL: "/application-administrator",
   COMPANY_PROFILE_URL: "/company-profile"
};

export const tokenValidity = {
   convertToMilliSeconds: 1000,
   oneMinuteInMilliSeconds: 60000,
   checkUserDetailsInterval: 10000
};

